name: Release

on:
  push:
    branches:
      - master
      - main
      - alpha
      - beta
      - next
      - "next-major"
      - "+([0-9])?(.{+([0-9]),x}).x"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Lint, test and compile
        run: |
          npm ci
          npm run prettier
          npm run lint
          npm run test
          npm run compile
        env:
          CI: true

      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action@sha256:43a9e5ce88fc0460c22f3f3c45e39ac99e1cefff2ffd76c6e8c34306c8ccec91
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Dump semantic outputs
        if: steps.semantic.outputs.new-release-published == 'true'
        run: echo "$SEMANTIC_OUTPUTS"
        env:
          SEMANTIC_OUTPUTS: ${{ toJson(steps.semantic.outputs) }}
